### Question 1
What's the version of Pandas that you installed?

In [2]:
import pandas as pd
pd.__version__

'1.5.3'

### Getting the data
For this homework, we'll use the California Housing Prices dataset

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 21:05:00--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 198.18.0.12
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|198.18.0.12|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  1.11MB/s    in 1.2s    

2023-09-18 21:05:04 (1.11 MB/s) - ‘housing.csv’ saved [1423529/1423529]



### Question 2
How many columns are in the dataset?

In [8]:
df= pd.read_csv('housing.csv')
df.shape[1]

10

### Question 3
Which columns in the dataset have missing values?

In [10]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

### Question 4
How many unique values does the ocean_proximity column have?

In [13]:
df['ocean_proximity'].nunique()

5

### Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [14]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

### Question 6
- Calculate the average of total_bedrooms column in the dataset.
- Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
- Now, calculate the average of total_bedrooms again.
- Has it changed?

In [15]:
df['total_bedrooms'].mean()

537.8705525375618

In [16]:
df['total_bedrooms'].fillna(df['total_bedrooms'].mean()).mean()

537.8705525375617

### Question 7
- Select all the options located on islands.
- Select only columns housing_median_age, total_rooms, total_bedrooms.
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Compute the inverse of XTX.
- Create an array y with values [950, 1300, 800, 1000, 1300].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the value of the last element of w?

In [17]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [19]:
df_island= df[df['ocean_proximity'] == 'ISLAND']
df_col= df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']]
df_col.head()

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [20]:
X= df_col.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [21]:
X_T= X.T
X_T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [22]:
import numpy as np

XTX= np.dot(X_T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [23]:
y = [950, 1300, 800, 1000, 1300]

In [24]:
XTX_inv= np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [26]:
w= XTX_inv.dot(X.T).dot(y)
w[2]

5.699229455065575